spring:
  application:
    name: root

  datasource:
    url: ENC(6HdfE7MiNEDeDAQFxc9uXHr4wUvu6e5Hv0As1bL8/A+adPWS0DprN4X9Lhc8whHuLcjR/pR/za3CkoVsSdvysUj62GhFdmyD8zKxEaWeq6KPMi5arc5hTA==)
    username: ENC(M6dbJfAs8Z+1AT+4hN57O2txkg2eD09e)
    password: ENC(q10RQ+1XLOoorSTFbdfA0t3DFU+KhcWNeZgdgFEwYlI=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none # 엔티티 변경 시 데이터베이스 업데이트
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

server:
  servlet:
    context-path: /api
    encoding:
      force-response: true

schedule:
  chart:
    cron: 0 0/10 * * * *
    use: true

api:
  key: ENC(PA/+/7k86WByjLeMohtTxkdonVjWNG0+62phGNn/NCi0N649yx10LyeVXEGbRcgNcC44hf1qf9NlTNkbC0k+qpZXcffUYOmu8wUCKPuir3r6DdWKeSHKbSr6vfCOwsVJxmE6tTuUuv15d2f+Yfy6ZXkgsGmMR+NhuMsK5OrGexkLAMBD6EggRleoxc62nDTbof5B5vTN9Mg6Rs8QzkaG6bH2RQFrkwiT5Ryvj6kq2PI/hzlZ1P84P1dGOZCxjZP6lhpxM70+J04SnvQqboZMhq3e0W31yLhHmtiSaGkCQiawgAvETcQOzBg2DU7S4mQuLPFGbhYnXUFhm1+f3m2pVXsPVr2OkTiDajo011PdQ6XvPipFe8hSJkLhcb4nnRXMgAJgHgrMPi+//OP5xhSglKW3yATpn/CNLTaPnGKMjCIPY2ape0//zmAEo+1QnpZMlZxDUIooswgq0Qe1cbAD78VJyF9EJezYfFyzdWjtHvRG7N38x7vnKG/b7TaB1h3nxRdjHLx5M+qPhYs6fPihoZPznAkIhJ6HknzfnekiI6nE1PlWPHe3vU2PsG0AOE2wDL2x0JNeSquU6gNOWCphHBgbDrHeLT513KgjkyVmtpEC0mhIitW/M/4r6dNUt5Hzk/Htb95guvmovVBvyCVvwpxNarSlXfKtr8WnRloS0qYMkqzILXUPPn1kU+XVQdsCTaFzi0Zi9l103IYFeiswcwI+c4uBV8k9uFunGomImxfzqZUVLfQI673va8ZxKcVLpsG+EU/sQMeRWS4kInfbDKHcYjap9StKkqwXZlzzhcBO2zgTo9A5rgCeJXmFKL6cKxzNaTUUSv06zj8XYtj9q8QPzoDKzDXA)