spring:
  application:
    name: root

  datasource:
    url: ENC(xuMT3QjPMbBRvhic+tlqjbkGhXZA9962Jgux1h8fArYzb7xjWMcnxuflGLGab04a)
    username: ENC(AWlKQv+7LcqS0gZYzuLekw==)
    password: ENC(q10RQ+1XLOoorSTFbdfA0t3DFU+KhcWNeZgdgFEwYlI=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none # 엔티티 변경 시 데이터베이스 업데이트
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

server:
  servlet:
    context-path: /api
    encoding:
      force-response: true

schedule:
  chart:
    cron: 0 0 * * * *
    use: true
  book:
    cron: 0 15 0 * * *
    use: true
  upgrade:
    cron: 0 20 0 * * *
    use: true
  jewel:
    cron: 0 3 * * * *
    use: true
  gem:
    cron: 0 8 0 * * *
    use: true

api:
  key: ENC(PA/+/7k86WByjLeMohtTxkdonVjWNG0+62phGNn/NCi0N649yx10LyeVXEGbRcgNcC44hf1qf9NlTNkbC0k+qpZXcffUYOmu8wUCKPuir3r6DdWKeSHKbSr6vfCOwsVJxmE6tTuUuv15d2f+Yfy6ZXkgsGmMR+NhuMsK5OrGexkLAMBD6EggRleoxc62nDTbof5B5vTN9Mg6Rs8QzkaG6bH2RQFrkwiT5Ryvj6kq2PI/hzlZ1P84P1dGOZCxjZP6lhpxM70+J04SnvQqboZMhq3e0W31yLhHmtiSaGkCQiawgAvETcQOzBg2DU7S4mQuLPFGbhYnXUFhm1+f3m2pVXsPVr2OkTiDajo011PdQ6XvPipFe8hSJkLhcb4nnRXMgAJgHgrMPi+//OP5xhSglKW3yATpn/CNLTaPnGKMjCIPY2ape0//zmAEo+1QnpZMlZxDUIooswgq0Qe1cbAD78VJyF9EJezYfFyzdWjtHvRG7N38x7vnKG/b7TaB1h3nxRdjHLx5M+qPhYs6fPihoZPznAkIhJ6HknzfnekiI6nE1PlWPHe3vU2PsG0AOE2wDL2x0JNeSquU6gNOWCphHBgbDrHeLT513KgjkyVmtpEC0mhIitW/M/4r6dNUt5Hzk/Htb95guvmovVBvyCVvwpxNarSlXfKtr8WnRloS0qYMkqzILXUPPn1kU+XVQdsCTaFzi0Zi9l103IYFeiswcwI+c4uBV8k9uFunGomImxfzqZUVLfQI673va8ZxKcVLpsG+EU/sQMeRWS4kInfbDKHcYjap9StKkqwXZlzzhcBO2zgTo9A5rgCeJXmFKL6cKxzNaTUUSv06zj8XYtj9q8QPzoDKzDXA)
  public: ENC(vvdNzL6+BAgpJFSB8vk9WmPaB+AO7hROoqR4Sw6p2w6HnUOpT5qtENitthhKhavqR+jSGtQXjhKcq+1l8D7Mnv9UISGMclg9NeZomhb4oB1r4dxRMBwkIxoE+ygLm/Hm/Ed5s4R98bjzYK3i764gt7x6aS9kEEtlnubDJ5xO3qTuqVneEcniQjWuskP62aDp8zFkUWnEsSmgmaPadMq2yAx+YKrMKybkOzZOLeo7521RKud2DBMWv1f6dlKx/G0Z02keDFqVb/p586fFYpV9E/R58efdE+KyLWXPwfuIASpIvjBlqLVKB0My0WUfzmC2AWP8Rqjk+BRrp4mLP0S1pWSaAZTUIzx5V7yeRN/a9ogKRBOfktjQ9BJIFWDXFdHuswPkoNa1CbWu+Q23bqCkCsBcAl/Rd8iKJGejtuCkKmDqbsl2Im1zB+HkSpX1WwBP7TPrkqgokI1vue2dDFrn33TkBFdxOhoOF4I/o2lpAsbfUEGrZwo76Q0M9DxkPngjWWV/Agxgpc1IWPdLugyja50PJso0GIwWbHEKpZZDHhvqrg3SL4KlEdey9AHKuxmCBOVM6XD2JVT+baceSXShFxheJmt2FZZJSYfF9u4BlNDGHE8SqYwt7pGKMrvae4PyRlQ6nhIsXYUzijI27keSWs7tKwDOwxzx92AQnZJjQw3DKYCRgYeuK89+zkrLCXv4SuE5iYgqo1wYacx4/Gy4x4PDjPiT1nnfRyW73pd+1WzaKeQAShHFNUuVorkrPcgrpIU6qiXM3guj47grcqUOFhmHjLetFkpwcJjEEYHa1b5HJ+7O/4yvjuiYkLLpWtQtCSADuZn7jYtlv7P4Q32vMjSf3GHB2oZN)
