spring:
  application:
    name: root

  datasource:
    url: ENC(6HdfE7MiNEDeDAQFxc9uXHr4wUvu6e5Hv0As1bL8/A+adPWS0DprN4X9Lhc8whHuLcjR/pR/za3CkoVsSdvysUj62GhFdmyD8zKxEaWeq6KPMi5arc5hTA==)
    username: ENC(M6dbJfAs8Z+1AT+4hN57O2txkg2eD09e)
    password: ENC(q10RQ+1XLOoorSTFbdfA0t3DFU+KhcWNeZgdgFEwYlI=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none # 엔티티 변경 시 데이터베이스 업데이트
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

server:
  servlet:
    context-path: /api
    encoding:
      force-response: true

schedule:
  chart:
    cron: 0 0/10 * * * *
    use: false

api:
  key: ENC(Dseb4BJVSFXMgG4NLhVUD/NIb82zVAhoMqC5SkSRCucdh0HNx2VmLwCeJ1L6V2oL4ZRAcxrfFPNlOD+8nXpU+TYI1FCepSV6fzKAg1Lq5WOC1tZi9qxkXbhEhT34u07DkuIMO+oQGDCRdygjzuIv8Gz/U5h3NOE/01VDIn44JY5vECnSnyHTQzoyYiysXqrDG3j2plmYrfkK8UegrQok8zEFRZE8R1ZiHm8hrygnz1WCyChXyrmGtWGaUwGcnU5eJT8w7rtN2Ppq2cSweeVUZKGKmW9PZ+7a+VZADhYZl6+YOPuB0N5Y9BarGJVAbLqgEb978OFogZ6SBXQanlymVPhACnajbG08XrHWlL+GKb/+BqABlTDVlot4KDXp4AHeb/dIILMeaS/aR1/JEYPPSZZ6C1jbcPGkCgmZGuu8NWoKq3+bfZ8CQP6M6BLhpOAMOnZcueXDSq/qW9TqGLVpT6PgVv1pRGF+bXZAZFq88v4qAOTrMwqAv01x7N3I0eH6dKA+pnNd2Xq6m1bqbbp2xGYMqY1QJUr52u85g+69WooMrqMW/sauQBgFeeaBAHoLduGJzkfV04/+nDqbAbQ8D5sO8bDWxdGGBZkAMSi84i1xPcnasBNEqlva/sQBnfed4vbjtbY9cv79M83hE2SxOA8MEmDe2RMIiIHCh2Cv8eQZJ0iucVc/HyK5OE/jXRKNUMJjEsENWVqQ87YupT4owl5M1fH3F53FbttxwAzBvENz73yG79RU6PU9CbS3P06E1bFk7TRb8maG7737MezFD2gYb0vrSLsU1DcANx578MlcTOS1bxUDyv6P6MEBf2R4Q+fzt3L3xv0GjJX9sLKvw2AXxgp9iwXb)